### ISSUE TITLE
0 */40 9-18 * * * execution error

### ISSUE THREAD

**Issue by perrylau** [ximtech/CronExpression#1]
Hi,

I set up a cron:"0 */40 9-18 * * *", which should be executed every 40 minutes. However, after the actual execution at 9:40, when the nextCronDateTime is used to calculate the next time, the returned result is 10:00, and the correct result should be 10:20.

**Comment by ximtech** [comment]
Hi. The "*/40" means that cron fires at every 40 minute of the hour.
So */15 would run at 9:00, 9:15, 9:30, 9:45, but */40 will run at 9:00 and 9:40.
This is a one of limitations of all cron systems. 
[Check Crontab](https://crontab.guru/#*/40_9-18_*_*_*)

**Comment by perrylau** [comment]
Thank you for your reply, I should have misunderstood it.
